api: "1.15"
name: ClueScrollManager
version: "${project.version}"
main: main.ClueScrollManager
api-version: 1.15
author: Izocel
softdepends: [Vault, ClueScrolls]
commands:
  scroll-upgrade:
    description: Used to upgrade scrolls to higher tiers scrolls
    usage: /scroll-exchange <tier:number> <amount:number>
  scroll-exchange:
    description: Used to exchange scrolls for coins
    usage: /scroll-exchange <tier:number> <amount:number>
